apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: myapp:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer

  # in this configuration file 
  # a deployment with three replicas and a service that exposes the deployment on port 80. 
  # kubectl apply 
  #   command can be used to apply this configuration file to a Kubernetes cluster.
